### PR TITLE
Many Updates

### PR DESCRIPTION
**Pull request by ekager**
Moving around DB code, some tests for DB code, UI Tests, admin and edit viewer flow, hardcoding the magic buttons to each fragment (They were finicky), updating some style (trying out some more modern elevated design with an appcompat work around, what do you think?)

### CODE REVIEW

**Review by asciimo — COMMENTED** [review]
Wow, so much! I'm looking forward to building this on the tablet. How do I run tests in Android Studio?

**Comment by ekager** [comment]
You right click on the test file and then select Run.

**Comment by asciimo** [comment]
Sorry it took me so long to get around to this. I recently upgraded to Android Studio 3.0 and I have all the SDKs from 17 up installed. I get this fatal when I try to run the app on the reference device (Asus TF700T, Android 4.2.1).

```
11-04 17:16:41.974 12078-12078/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: /data/app/com.sfvtech.payperview-1.apk
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:4820)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4430)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5039)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: /data/app/com.sfvtech.payperview-1.apk
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:4805)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4430) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5039) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by asciimo** [comment]
Not sure if your latest commit was complete, but here's a new exception:
```
11-05 12:37:15.455 3105-3105/com.sfvtech.payperview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.RuntimeException: Unable to get provider com.sfvtech.payperview.utils.PayPerViewFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.sfvtech.payperview.utils.PayPerViewFileProvider" on path: /data/app/com.sfvtech.payperview-2.apk
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:4820)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4430)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5039)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sfvtech.payperview.utils.PayPerViewFileProvider" on path: /data/app/com.sfvtech.payperview-2.apk
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                          at android.app.ActivityThread.installProvider(ActivityThread.java:4805)
                                                                          at android.app.ActivityThread.installContentProviders(ActivityThread.java:4430) 
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372) 
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5039) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by ekager** [comment]
Okay I updated the file path and cleaned on my machine and I am not getting any errors. Let me know if it's fixed for you now!

**Comment by asciimo** [comment]
Worked! Looking pretty slick, too.  I found a couple items I'll make issues for.

**Pull request merged**
